@baseURL = https://fivme3e3qg.execute-api.eu-central-1.amazonaws.com/prod
@spaceId = 2f49fd66-823f-4b65-9f5a-f67f5ec6710a

GET {{baseURL}}/hello/
###

POST {{baseURL}}/spaces/
Content-Type: application/json

{
  "location": "New-York",
  "name": "In USA"
}
###

GET  {{baseURL}}/spaces?spaceId={{spaceId}}
###