@baseURL = https://0a4918k216.execute-api.eu-central-1.amazonaws.com/prod

GET {{baseURL}}/hello/
###

POST {{baseURL}}/spaces/
Content-Type: application/json

{
  "location": "Kyiv",
  "name": "In Ukraine"
}
###

GET  {{baseURL}}/spaces/
###